### ISSUE TITLE
Add an Exit button and Power button

### ISSUE THREAD

**Issue by robert5974** [rsjudka/intelligent-auto#11]
Could it be possible to add a button that exits the IA app and possibly a button for power options (Shutdown, reboot)?

**Comment by rsjudka** [comment]
yep so I added these in when I was making the other change, also available in the `develop` branch.

In the main window, you'll see a save button (which saves the state of the app), a power button (which shuts down the system on click and reboots the system when you click and hold for 2 seconds), and an exit button.

**Comment by robert5974** [comment]
Sounds good.  I'll build IA again shortly after my clean image finishes updating.  I'll report back.

**Comment by robert5974** [comment]
Built with the develop branch and I like the clean implementation of the additional buttons.  It shutdown really quickly.  The exit button worked well.  I forgot you said rebooting was to hold it for 2 secs.  I'll give that a try once I fix whatever I've done with the xserver.

**Comment by robert5974** [comment]
I tried the reboot function and that worked. Closing the issue.  Thanks!👍
