### ISSUE TITLE
Error Building

### ISSUE THREAD

**Issue by robert5974** [rsjudka/intelligent-auto#17]
While building, on "make" command, I am getting an "error 2" at the end.  Before failing it has an error of:

'Class fix::openauto::autoapp::service::ServiceFactory' has no member named 'resize'
   inline void resize() { this->service_factory.resize(); }
Is this from a recent change maybe?  I see the fullscreens option was added 2 days ago.

**Comment by robert5974** [comment]
This was for building from the develop branch.

**Comment by rsjudka** [comment]
Did you also pull the latest develop branch for OpenAuto?

**Comment by WardBenjamin** [comment]
I ran into this earlier today; cloning the develop branch of intelligent-auto doesn't automatically use the develop branch of OpenAuto. Like @rsjudka says, you can check out the develop branch of his OpenAuto fork.

**Comment by WardBenjamin** [comment]
If you run into an issue missing taglib, you'll need to install libtag1-dev. I assume this is for the local media player capability. 

I almost opened a pull request to add this to the dependency list before I realized it had already been handled in the development branch :)

**Comment by rsjudka** [comment]
Yeah sorry I guess I should have made this more obvious.
Since I'm using submodules for aasdk and OpenAuto, anytime I make changes to those repos you'll have to do a recursive clone/pull to get all the needed changes (if there are any).

**Comment by robert5974** [comment]
Ah, that makes sense.  Thanks.  I'll run it back.  I built it a few days ago but I got a black screen from openauto.  I just started on a fresh image on a bigger sd card on rpi.

**Comment by robert5974** [comment]
Alright I got it built after updating the openauto submodule.  Thanks.  I still experience the crash in AA.  Is that still the case for everyone?

**Comment by rsjudka** [comment]
Awesome! Yeah there's a possible fix for it floating around, I was planning on porting it in and testing it soon.

**Comment by robert5974** [comment]
That's great news!  Btw, I tried out the Bluetooth media player and that is working very well.  Is the full screen implementation actually working?  I wasn't sure how that is to be activated.

**Comment by rsjudka** [comment]
Sweet! I had some issues with Bluetooth (mainly because I couldn't handle the authentication in my app). I'm assuming you got a notification or something from your Bluetooth manager?

Try double tapping on the OpenAuto window to toggle fullscreen.

**Comment by robert5974** [comment]
Yeah I installed blueman like recommended.  It gave some error at first but
the pairing window was behind that and once I accepted the pairing it
connected with no issue.

I did notice that if I wasn't on the music app on my phone then pressing
the play button in the IA media player didn't do anything but if on the app
then it passes and plays fine.  No big deal.

Only thing is you can't choose an artist, album, or song except from the
phone.  The ability to do so isn't advertised or anything like that so it's
not a big deal.

I'll close the issue if you don't have anything else.

Robert Crowley

**Comment by skewty** [comment]
comments on an issue are typically to add more reference details about the issue.  Discussion about the issue is usually on Slack / Mattermost / Tulip...    Have you guys considered getting a free Slack instance to chat about this?

**Comment by rsjudka** [comment]
@robert5974 yeah unfortunately the bluetooth integration won't be that great since im really only able to query Title/Artist/Album data and can only send prev/next and pause/play requests. Unless you know of any bluetooth players that do allow you to actually control playlists? When poking around dbus it does look like I can get/set the position of the song, so maybe ill add a scrubber to it (similar to how the local media player has).

I also did notice that, and it seemed totally dependent on when the phone "allows" the audio to be controlled. Usually the phone has to already be playing music or have something queued up.

**Comment by rsjudka** [comment]
@skewty yeah thats a good idea, right now everything is just kinda all over the place and i tend to lose things that have been said :p

**Comment by robert5974** [comment]
It's all good.  I was just testing it and giving some feedback.  I don't know of any with that functionality without digging around.  I wasn't exactly looking around for it but if I come across one I'll let you know.  Thanks!
