### ISSUE TITLE
Settings page for open auto cut off

### ISSUE THREAD

**Issue by rhysmorgan134** [rsjudka/intelligent-auto#23]
As above, on the latest build the settings page for open auto look like they arent responsive enough. This is running on the official 7 inch touch screen (800x480)

![ia](https://user-images.githubusercontent.com/36861722/79025296-419a9680-7b7d-11ea-9f42-b4a76c751f6f.PNG)

**Comment by rsjudka** [comment]
Yeah I should have mentioned somewhere in the README but you'll want to be using the develop branch for all the latest features (this has been fixed there).

Things have just been moving so fast and I haven't really decided how I wanted "releases" to go, but for now I would recommend always using the develop branches (make sure to use the corresponding branches for aasdk and openauto too).
