### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by yoriaantje-dev** [rsjudka/intelligent-auto#3]
I can't seem to install based on the new commands, installing on RPi3B+ with clean OS installation. 
Problem occors when using the cmake to build, seems to be related to the dependicies part of the file.

**Comment by yoriaantje-dev** [comment]
I'll provide debugging info when able

**Comment by rsjudka** [comment]
if you can provide the cmake output i can try to help debug this issue

**Comment by yoriaantje-dev** [comment]
[CMakeError.log](https://github.com/rsjudka/intelligent-auto/files/4319032/CMakeError.log)
[CMakeOutput.log](https://github.com/rsjudka/intelligent-auto/files/4319033/CMakeOutput.log)
These are the automatically generated files, CMake suggested I'd send these for debugging

**Comment by rsjudka** [comment]
@yoriaantje-dev did you clone the dependencies as well? It looks like you're missing the OpenAuto stuff.

**Comment by yoriaantje-dev** [comment]
@rsjudka no, I've cloned only your repository. I didn't see any other repository's that I'd have to clone. If you were to tell me which ones, preferably with links, that be nice.

Also, please tell me what I need to do with the newly cloned repository's and were I need to put them. I've made a folder which contains your repo, so I'd guess alongside your repo in the folder AAProject?

**Comment by rsjudka** [comment]
@yoriaantje-dev so I've actually made it super easy and have aasdk and OpenAuto as submodules.

If you run this command:
`git clone --recursive https://github.com/rsjudka/intelligent-auto.git`
You should get all the files in the right locations. Then you can just run the build process and be good to go!

**Comment by yoriaantje-dev** [comment]
Yes! This worked perfectly, after installation (which took a while) everything seems to be working.
I do have connection issues, but I'll be opening a seperate issue for this.

@rsjudka I do suggest adding this command to your readme containing the installation instructions, regardless, thanks for the help!
