### ISSUE TITLE
[Enhancement] send kill command to apps open in app launcher

### ISSUE THREAD

**Issue by rhysmorgan134** [rsjudka/intelligent-auto#39]
Currently if you close down ia and are using the app launcher, the launched app will continue to be open in the background.

I can verify this by being unable to use the port that is used by my app even once ia is shut down. If I manually kill the app in ia using my apps close button, the port is released, would be a nice QOL change if possible.

Thanks as always!

**Comment by rsjudka** [comment]
i knew this was a problem but never expected anyone to actually run into it hah since i assumed most people wouldn't really close ia

the reason i haven't done much in terms of ia cleanup on exit is that there is currently a bug in openauto that causes a seg fault on destruction, and was planning on cleaning things up when then gets solved

i can go ahead and add the destructor for the launcher at least, but in the meantime you should be able to work around this by manually closing the app before exiting ia (clicking the X basically sends a SIGTERM)

**Comment by rhysmorgan134** [comment]
Yeah to be honest in day to day use its really not an issue. Its only when I am developing my app, ia auto opens on boot, I close it, begin making my changes, my development app then uses a different port for the server, but the client then loads the files from the original instance of the app. I then spend ten minutes freaking out why my changes haven't happened, before realising its happened to me for the 100th time :joy:

but yeah its really not a problem as I have the close button still built into it anyway, so no rush at all!

on a seperate note, do you have any pointers as to where I can find the hex colour for the horizontal rule in the picture below? been browsing through your style sheets, but I can't seem to spot it,

![image](https://user-images.githubusercontent.com/36861722/83879047-f3e17b00-a734-11ea-8f3b-fbaa9bbea658.png)

**Comment by rsjudka** [comment]
hah sorry :p 

So yeah Qt doesnt have a horizontal rule, so i kinda had to hack it together. Its basically just a really thin QFrame lol
```
QFrame[frameShape="4"][frameShadow="16"],
QFrame[frameShape="5"][frameShadow="16"] {
    color: rgba(255, 255, 255, 31);
}
```

**Comment by rhysmorgan134** [comment]
perfect, thankyou

put these on by the way today, in the settings page on the second one, I think im pretty close to matching your style!

https://youtu.be/wKBC56UhK64

https://youtu.be/o7TGF2G8eGw

**Comment by robert5974** [comment]
Your setup looks clean in the video.  I'm liking it.  I probably need to try your app again as I didn't do much with it when testing the app-launcher on the first go around.  Great job and @rsjudka for the development.  On point with the requests.

**Comment by rsjudka** [comment]
@rhysmorgan134 fix now in develop that will kill the running process on destruction!

**Comment by rhysmorgan134** [comment]
Thankyou 👍
