### ISSUE TITLE
Problems with some apps

### ISSUE THREAD

**Issue by leobel96** [rsjudka/intelligent-auto#4]
I have tested the installed software and it works! Anyway please add these suggestions in readme:
- After XFCE installation reboot the system
- Run the program as `sudo ./ia`
The preinstalled apps work well but I have installed two third-party apps compatible with Android Auto and they don't work as expected: Telegram and VLC. The first one keeps loading and nothing happens while the second one shows the message "The app is not compatible" and doesn't work.

**Comment by rsjudka** [comment]
1) I can maybe put together a guide for helping setup XFCE. Its not really a requirement, more so if you want the "fake" brightness to work lol

hmm i wonder if any 3rd party apps are supported by OpenAuto... do you happen to know if those apps work with a real Android Auto?

**Comment by leobel96** [comment]
Unfortunately I don't have a real Android Auto but they are pretty popular and updated apps, I think they work

**Comment by yoriaantje-dev** [comment]
Didn't Google release a site with supported apps? I seem to recall finding something along those lines in the Android Auto app on my phone some time ago...

**Comment by leobel96** [comment]
Yes they are supported. I understood you were asking me if the apps have the same bug also in real Android Auto ahahah. Sorry.

**Comment by leobel96** [comment]
@rsjudka I have tested again the two apps and I have found that the VLC problem was caused by the fact that I hadn't completed the initial configuration in the app: after the configuration it worked like a charm. The telegram problem appears only sometimes and closing/reopening ia and/or telegram android app solves it.

**Comment by rsjudka** [comment]
I wonder if the telegram issue is related to that crash that everyone else has been seeing... Could you attach the console output of a time it fails?

**Comment by rsjudka** [comment]
@leobel96 I just merge a fixed into `aasdk` develop branch to fix a crash caused by some message channels getting interleaved. Could you test out with that and see if your telegram issue?

Or if that's no longer an issue feel free this close this issue.

**Comment by leobel96** [comment]
@rsjudka Have I to remove the prevous installed version of intelligent-auto in some way or cloning the develop branch and installing it using the installation steps in README is enough?

**Comment by rsjudka** [comment]
nope you don't have to remove anything. If you do a recursive checkout of the develop branch you should be able to just run the `make` command within the build directory. The only thing is you might need to install some additional packages (i think libtag is the only one) as that was something added in the new branch.

**Comment by leobel96** [comment]
Hello @rsjudka . I am sorry but I had many commitments and forgot to test it. Today I tried to build the new version many times but I keep getting this error:

```
[ 83%] Building CXX object CMakeFiles/ia.dir/src/app/config.cpp.o
[ 83%] Building CXX object CMakeFiles/ia.dir/src/app/tabs/data.cpp.o
In file included from /opt/vc/include/interface/vcos/vcos.h:144,
                 from /opt/vc/src/hello_pi/libs/ilclient/ilclient.h:47,
                 from /home/pi/intelligent-auto/openauto/include/f1x/openauto/autoapp/Projection/OMXVideoOutput.hpp:24,
                 from /home/pi/intelligent-auto/openauto/include/f1x/openauto/autoapp/Service/ServiceFactory.hpp:23,
                 from /home/pi/intelligent-auto/include/app/tabs/openauto.hpp:16,
                 from /home/pi/intelligent-auto/include/app/window.hpp:14,
                 from /home/pi/intelligent-auto/src/app/tabs/data.cpp:5:
/opt/vc/include/interface/vcos/vcos_logging.h:234:39: warning: ISO C++ does not permit named variadic macros [-Wvariadic-macros]
 #  define _VCOS_LOG_X(cat, _level, fmt...)   do { if (vcos_is_log_enabled(cat,_level)) vcos_log_impl(cat,_level,fmt); } while (0)
                                       ^~~
In file included from /home/pi/intelligent-auto/aasdk/include/f1x/aasdk/USB/IUSBWrapper.hpp:24,
                 from /home/pi/intelligent-auto/aasdk/include/f1x/aasdk/USB/AccessoryModeQueryChain.hpp:21,
                 from /home/pi/intelligent-auto/include/app/tabs/openauto.hpp:6,
                 from /home/pi/intelligent-auto/include/app/window.hpp:14,
                 from /home/pi/intelligent-auto/src/app/tabs/data.cpp:5:
/usr/include/libusb-1.0/libusb.h:740:46: warning: ISO C++ forbids zero-size array ‘dev_capability_data’ [-Wpedantic]
  uint8_t dev_capability_data[ZERO_SIZED_ARRAY];
                                              ^
/usr/include/libusb-1.0/libusb.h:765:78: warning: ISO C++ forbids zero-size array ‘dev_capability’ [-Wpedantic]
  struct libusb_bos_dev_capability_descriptor *dev_capability[ZERO_SIZED_ARRAY];
                                                                              ^
/usr/include/libusb-1.0/libusb.h:1258:70: warning: ISO C++ forbids zero-size array ‘iso_packet_desc’ [-Wpedantic]
  struct libusb_iso_packet_descriptor iso_packet_desc[ZERO_SIZED_ARRAY];
                                                                      ^
In file included from /home/pi/intelligent-auto/include/app/window.hpp:14,
                 from /home/pi/intelligent-auto/src/app/tabs/data.cpp:5:
/home/pi/intelligent-auto/include/app/tabs/openauto.hpp: In member function ‘void OpenAutoWorker::resize()’:
/home/pi/intelligent-auto/include/app/tabs/openauto.hpp:32:50: error: ‘class f1x::openauto::autoapp::service::ServiceFactory’ has no member named ‘resize’
     inline void resize() { this->service_factory.resize(); }
                                                  ^~~~~~
make[2]: *** [CMakeFiles/ia.dir/build.make:157: CMakeFiles/ia.dir/src/app/tabs/data.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:108: CMakeFiles/ia.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

If you prefer I can open a new issue.

**Comment by rsjudka** [comment]
you'll need to update your submodules branch in order for this to build.

You should be able to run this command in the root of ia and get it building again:
```
git submodule update --recursive --remote
```

**Comment by leobel96** [comment]
> you'll need to update your submodules branch in order for this to build.
> 
> make sure you're on the develop branch of ia.
> 
> You should be able to run this command in the root of ia and get it building again:
> 
> ```
> git submodule update --recursive --remote
> ```

@rsjudka  You were right, now it installed successfully.
I can confirm I have no more problems with telegram. I think this issue can be closed. Anyway I suggest you to add to README that `ia` has to be run using `sudo` or android auto doesn't work.

**Comment by rsjudka** [comment]
> I suggest you to add to README that ia has to be run using sudo or android auto doesn't work

So its not necessarily required to run with sudo (I never do) but depending on your setup you may need to. If you're having issues with it, you might also want to check the permissions on the openauto config files as i noticed if those are written as sudo then it'll crash.

**Comment by leobel96** [comment]
@rsjudka maybe you can add to the README that it **could** be necessary to run `ia` with `sudo`. It seems a good compromise.
