### ISSUE TITLE
Brightness control not working

### ISSUE THREAD

**Issue by yoriaantje-dev** [rsjudka/intelligent-auto#43]
Hi! 

I saw in #9 you asked me to test screen'brightness..
unfortunally i didnt notice this, sorry about that

Yesterday when i drove at night i noticed no brightness control working?
Im on today's development branch, official RPI 7inch touch

Maybe I'm missing something?

**Comment by rsjudka** [comment]
In the settings page, did you see the brightness module to the rpi 7" one?

**Comment by rsjudka** [comment]
so the rules helped get it to work?

sorry without an actual rpi screen to test with i did not know this would be an issue, should definitely be noted somewhere tho

**Comment by yoriaantje-dev** [comment]
> so the rules helped get it to work?
> 
> sorry without an actual rpi screen to test with i did not know this would be an issue, should definitely be noted somewhere tho

Urhm yes, forgot that this issue was open!
