### ISSUE TITLE
Issue when Building

### ISSUE THREAD

**Issue by yoriaantje-dev** [rsjudka/intelligent-auto#47]
Hi everyone,

I can't seem to build the latest development version...

This is the error:
```
CMake Error at /usr/lib/arm-linux-gnueabihf/cmake/Qt5/Qt5Config.cmake:28 (find_package):
  Could not find a package configuration file provided by "Qt5Qml" with any
  of the following names:

    Qt5QmlConfig.cmake
    qt5qml-config.cmake

  Add the installation prefix of "Qt5Qml" to CMAKE_PREFIX_PATH or set
  "Qt5Qml_DIR" to a directory containing one of the above files.  If "Qt5Qml"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  openauto/CMakeLists.txt:33 (find_package)


-- Configuring incomplete, errors occurred!
```

These are the commands I run to update to a newer version of IA
```
sudo su (maybe not needed, but prevents errors and I don't mind)
cd (go to root dir)
rm -r /home/pi/intelligent-auto-dev (remove old files)
cd /home/pi (goto home dir for RPi)
git clone -b develop --recursive https://github.com/rsjudka/intelligent-auto.git intelligent-auto-dev (clone latest dev branch into intelligent-auto-dev (folder name I prefer, no other reason))
cd /home/pi/intelligent-auto-dev (go into the folder)
mkdir build (rest of the install commands, provided by you guys :))
cd build
cmake -DCMAKE_BUILD_TYPE=Release ../ -DRPI_BUILD=TRUE
make (---> Error occurs after the make command...)
echo done
```

**Comment by yoriaantje-dev** [comment]
Just tried the install script, it gives the same CMake error.

**Comment by rsjudka** [comment]
Oh shoot yeah in the recent change from PR#33 you'll need to install a few additional qt packages (you can see what those packages are in the PR)

will need to update the script for those changes as well

**Comment by yoriaantje-dev** [comment]
Urhm... What is PR#33? 😄

**Comment by yoriaantje-dev** [comment]
Pull Request #33, got it haha

Thanks for the help!

**Comment by rsjudka** [comment]
Dang hoping it would link the PR lol

https://github.com/rsjudka/intelligent-auto/pull/33

You'll see in the description what additional packages need to be installed

**Comment by rsjudka** [comment]
Feel free to reopen if that doesn't solve your problem

**Comment by yoriaantje-dev** [comment]
Nah, it worked. Personnally not going to switch to gstreamer yet tho. I'll do that next update.

**Comment by rsjudka** [comment]
Also if you have the time I would recommend building with the new gstreamer

Its alot smoother than the omx player and allows us to show popups over OpenAuto (soon I think I'd want IA to only use gstreamer to minimize the maintenance of it)

**Comment by rhysmorgan134** [comment]
I'll look into updating the script with the new requirements, I'll get an argument that can be passed to enable/disable gstreamer.

**Comment by yoriaantje-dev** [comment]
@rsjudka 
> Also if you have the time I would recommend building with the new gstreamer

Yeah, you naled the issue haha. In about 2-3 weeks I'll be done for this semester, allowing me to switch over and hopefully contribute more.

**Comment by rsjudka** [comment]
It's a bit concerning tho that it failed to build even though it wasn't built for gstreamer.

I'll look into this and see if something isn't conditionaled correctly
