### ISSUE TITLE
openauto stay blank

### ISSUE THREAD

**Issue by iztoogood** [rsjudka/intelligent-auto#55]
Hi,
do you have any advice for me ?
once started, when i plug my phone, the message "waiting for device..." disappear, but the window stay blanck 
I have tried to change display driver opengl in raspi-config with no effect

**Comment by rsjudka** [comment]
Did you set the dev rules correctly?

You might want to check out https://github.com/openDsh/dash

It's a bit more experimental, but stable enough for daily use plus it's got a lot more features and includes a script to help set everything up for you (as soon as we finalize everything there, this project will become deprecated)

**Comment by iztoogood** [comment]
thanks for your help
abou tdev rules...? you mean 
```
FILE=/etc/udev/rules.d/51-iadash.rules
echo "SUBSYSTEM==\"usb\", ATTR{idVendor}==\"*\", ATTR{idProduct}==\"*\", MODE=\"0660\", GROUP=\"plugdev\"" | sudo tee $FILE
```
--> yes it's ok

the git i have clone is :
git clone --recursive -b develop https://github.com/rsjudka/intelligent-auto.git

i will try right now https://github.com/openDsh/dash
thanks !

**Comment by iztoogood** [comment]
i have made multiple tests...

```
git clone --recursive https://github.com/rsjudka/intelligent-auto.git
+ cd intelligent-auto
+ wget https://raw.githubusercontent.com/rsjudka/intelligent-auto/develop/install.sh
+ chmod +x install.sh
+ ./install.sh
```
--> the .sh ends and... it works !!! \o/
everything is diplayed on the screen !!!
but the sound level cursor take too much place... on a small 3.5" lcd screen :-(

```
git clone -b develop --recursive https://github.com/rsjudka/intelligent-auto.git
+ cd intelligent-auto
+ ./install.sh
```
--> the .sh ends, ia is diplayed with new features... but openauto stay blancks (the phone is detected because the message "waiting for device..." desapear ... but the frame window stays blank)

```
git clone https://github.com/openDsh/dash 
+ ./install.sh ends with :
```

```
.../...
[100%] Built target aasdk
Aasdk Make completed successfully

make: *** Aucune règle pour fabriquer la cible « install ». Arrêt.
Aasdk install failed with code 1
```
the .sh do not ends :-(

in the meantime...
this script gaved me a working openauto :  
https://github.com/humeman/openauto_patched_installer
but only openauto... :-(

i really would like to make yours working with the ODBII functionality !!! ... and media player ... and all your stuff

**Comment by rsjudka** [comment]
have you tried running the autoapp build from intelligent-auto or the openauto in the openDsh org? That way we can isolate to either openauto or ia/dash

Did you remove all instances of aasdk/openauto before running the dash script? If not, I can see how that script would fail since it might be using a different version of aasdk that doesnt include the install logic. Basically if you start with a clean slate, you should be able to run the dash script without any issues

**Comment by iztoogood** [comment]
@rsjudka 
i have tried ... 
to first start dash ia and autoapp first before to plug my phone
to first start the app android auto with a road trip setted in maps before to plug the phone
in short ... all sort of combiantions ... first ia, first openauto app phone.. with pi user, as sudoer...

that's why...
i have totaly cleaned my raspberry from scratch...
currrently trying to get back both hdmi and LCD35-show running simultaneously ... with a decent resolution (i don't remember how i managed to do it before :-(  )
as soon as i'm back on dash installation... i'll give you some news.

@rhysmorgan134 
before that ... i've tested 
to go to settings > open auto > then turn rtaudio off
as well in ia openauto settings and autoapp settings... as pi user or as sudoer
it had no effect

as soon as i have fresh meat... i'm back

**Comment by iztoogood** [comment]
Hi it's me ... again...
my last test:
no changes...
but i have notice some new littles details...


https://github.com/openDsh/dash
leaves some binaries in `/usr/local/bin` (autoapp and btservice) is that normal ?

I have 3 ways to watch my desktop :
 - an hdmi screen
 - a little 3.5 touch LCD
 - and x11vnc

With a working autoapp, while the phone is plugged : openauto is shown on both screen whereas x11vnc stays on the autoapp splashScreen (with setting buttons etc ), on screens, the splashScreen goes in background

With the dash autoapp build, while the phone is plugged: all display as well x11vnc turn blanck, the splashscreen goes in back ground

**Comment by rsjudka** [comment]
> leaves some binaries in /usr/local/bin (autoapp and btservice) is that normal ?

Yep, that's so you can run the apps from anywhere on your system (by just typing `autoapp` for example)

Overall, I don't think x11 forwarding is supported by the actual android auto "video" that is displayed, so that behavior makes sense

As for dash build, @rhysmorgan134 did some debugging and found that you need to disable "rtaudio" in order for it to work. Seems to be an issue with the latest version of Raspbian, but still need to dig further there. Can you run it with that disabled and let me know how that works for you?

**Comment by iztoogood** [comment]
Hi,
I have disabled rt audio, it had no effect... maybe less messages in logs... but no effect on the blank screen
i diabled it ... in dash=> openauto settings 
and in autoapp settings, it's a radio button with the alternative choice "Qt" ... that i choosed...

all of this ... as pi or sudoed ...

**Comment by rsjudka** [comment]
Just for completeness,

When you disabled it, did you save and then restart the application? Changes to the openauto config don't take place until the next run

**Comment by rhysmorgan134** [comment]
I'm at a loss at what to suggest, I have built the latest commit twice and also have had someone else build it successfully. 

You shouldn't need to touch auto app at all, just the install script, and then run it with the /bin/ia

I would suggest a fresh raspbian install, and then follow those steps. There shouldn't be any need for sudo (this has caused issues for me in the past)

**Comment by iztoogood** [comment]
2020-05-27-raspios-buster-lite-armhf.zip
 \+ sudo apt-get install raspberrypi-ui-mods

... that's my rapsbian fresh from 2 days ...

ok it's enought for me to dirty a fresh install ;-) ...

i currently do an other test... if it does not work, il try from a raspbian with desktop OS ...
whohoo !! \o/ 
there is a new one ! `2020-08-20-raspios-buster-armhf.zip`

**Comment by iztoogood** [comment]
Hello,
Good news: It Works !!!

I'm really sorry I wasted your time,
but the saddest thing is that ... I can't really say what fixed my problem ...

Once again I completely reinstalled raspbian (buster) ...
previously I used the minimal install + raspberrypi-ui-mods
This time, I used the basic one with the desktop
it's a line of thought

In the same time I have insatlled my tiny LCD35 with another method

Thanks for your help and support, the issue can be closed ... it was on my side

**Comment by rsjudka** [comment]
just glad you got it working :)

you did help us a find an issue tho, which is helpful!

btw, did you end up using openDsh, or stuck with intelligent-auto?

**Comment by iztoogood** [comment]
The ia i have managed to install is openDsh
I now have to go ahead ... testing my bluetooth odb dongle ... wire a cam...
buying a bigger screen beacause 3.5 is really too small...

i have a new requet ... a feature addition ...
May you add https://github.com/miegl/PiFmAdv
it's a fork off piFm ... but this one allow to choose the gpio for the antena wire (usefull while using small tft screen) ... and it can broadcast messages over rds

**Comment by rsjudka** [comment]
yeah if you wanted to open up a request in dash that would be great!

luckily I have a UI element created for a radio, just haven't had anything to connect to it yet
