### ISSUE TITLE
Crash if clicking mic

### ISSUE THREAD

**Issue by leobel96** [rsjudka/intelligent-auto#7]
I have Google Assistant disabled on my Android smartphone and, if I click che microphone button of the Android Auto interface, it crashes and I have to unconnect/connect the cable again. A message saying "You have to enable Google Assistant on your smartphone in order to use this feature" would be great in my opinion.

**Comment by rsjudka** [comment]
Unfortunately, I don't have control over the actual Android Auto interface so I can't manipulate it in any sort of way... I could add some more gotchas pertaining to that tho
Thanks for pointing this out to me!

**Comment by leobel96** [comment]
I thought it was a problem of OpenAuto and, so, you could fix it

**Comment by rsjudka** [comment]
oh i meant about adding the "You have to enable Google Assistant on your smartphone in order to use this feature" message. Or maybe OpenAuto does generate the UI too? To be honest I havent looked that deep into it hah
I havent ran into this or seen it mentioned before, but I can look into it and see how I can handle it in OpenAuto so that it doesnt crash

**Comment by leobel96** [comment]
I meant to show the message on OpenAuto UI but, honestly, I don't know if OpenAuto generates the UI

**Comment by rsjudka** [comment]
so I just did some testing, but I wasn't able to reproduce your issue. I'm wondering if this was somehow related to all the other crashes (since it plays audio when clicking the mic) and thus has been fixed.

Let me know if this is no longer an issue and we can get this closed!

**Comment by leobel96** [comment]
I tested it now and the issue seems fixed. Great work! I also noticed that double-clicking Android Auto makes it full screen but it is not mentioned in the README. Please add it!
